<div class="container mt-5">

    <div class="card tarjeta-partido">

        <div class="card-body">

            <h2 class="titulo-equipos">
                <?= $partido->equipo_local ?>
                vs
                <?= $partido->equipo_visitante ?>
            </h2>

            <p class="info-partido">
                <strong>Fecha:</strong>
                <?= $partido->fecha ?>
            </p>

            <p class="info-partido">
                <strong>Estadio:</strong>
                <?= $partido->estadio ?>
            </p>

            <a href="<?= BASE_URL ?>partidos"
                class="btn btn-primary">
                Volver
            </a>
            
                <a href="<?= BASE_URL ?>partidos/editar/<?= $partido->id_partido ?>"
                    class="btn btn-warning">
                    Editar
                </a>
                <a href="<?= BASE_URL ?>partidos/eliminar/<?= $partido->id_partido ?>"
                    class="btn btn-danger"
                    onclick="return confirm('¿Estás seguro de eliminar este partido?')">
                    Eliminar
                </a>

        </div>

    </div>

</div>

<?php include './templates/partidos/footer.phtml'; ?>